@startuml Sequence Diagram

actor User


User ->> InputHandler : Keyboard

activate InputHandler

InputHandler -> InputHandler : ValidKey

InputHandler -> InputHandler : Encode Output Values To CAN

InputHandler -> EngineSimulator : Send CAN Frame

deactivate InputHandler

activate EngineSimulator

EngineSimulator -> EngineSimulator : Decode Input CAN Message

EngineSimulator -> EngineSimulator : Update Signals (Speed, RPM, EngineStatus, Gear)

EngineSimulator -> EngineSimulator : Encode Output Values (Speed, RPM, Engine Status, Gear) to CAN

EngineSimulator -> GUI : Send CAN Frame

deactivate EngineSimulator

activate GUI

GUI -> GUI : Show cool stuff

@enduml